# Generated by Django 2.2.6 on 2020-02-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RailwayJobsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('post_name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('total_post', models.IntegerField()),
                ('location', models.CharField(max_length=50)),
                ('last_date', models.DateField(max_length=100)),
            ],
        ),
    ]
